EnzymeAD/Enzyme

- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/FunctionUtils.cpp
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/GradientUtils.h
- enzyme/Enzyme/MustExitScalarEvolution.cpp
- enzyme/Enzyme/MustExitScalarEvolution.h
- enzyme/Enzyme/Utils.h
This restores Enzyme's ability to build against LLVM-6. We still should recommend against using LLVM-6, however, as it is not tested in CI (ubuntu doesn't have a package for) and a nontrivial amount of bugs in TBAA on the LLVM side.
> Partial LLVM-6 support

- enzyme/Enzyme/ActivityAnalysis.cpp
- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/CMakeLists.txt
- enzyme/Enzyme/Clang/EnzymeClang.cpp
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/Enzyme.h
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/EnzymeLogic.h
- enzyme/Enzyme/FunctionUtils.cpp
- enzyme/Enzyme/FunctionUtils.h
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/GradientUtils.h
- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
- enzyme/Enzyme/TypeAnalysis/TypeTree.h
- enzyme/Enzyme/Utils.h
- enzyme/test/Enzyme/cuda.ll
- enzyme/test/Integration/vecmax.c
- enzyme/test/TypeAnalysis/cpuid.ll
- enzyme/test/TypeAnalysis/cuda.ll
- enzyme/test/lit.cfg.py
This introduces a ClangEnzyme.so for loading directly into clang (necessary for ease of use with GPU backend). Introduces primitive support for PTX backend among various type and activity analysis updates. Also fixes pre and post Enzyme optimizations to work across various LLVM versions
> Easier Clang Integration, Type Analysis Updates, & Primitive Cuda support

- enzyme/Enzyme/ActivityAnalysis.cpp
- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/CMakeLists.txt
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
- enzyme/Enzyme/Utils.cpp
- enzyme/Enzyme/Utils.h
To follow #76 
Introduces helper utilities `__enzyme_float(ptr, size)` `__enzyme_double(ptr, size)` `__enzyme_integer(ptr, size)` and `__enzyme_pointer(ptr, size)` which explicitly informs type analysis of the type of [ptr, ptr+size).
Begins use of optimization remarks to provide debug information where type information not able to be determine. This allows source-code information about where type information needs to be injected.
> Additional tools to ease debugging of errors produced by Enzyme

- enzyme/Enzyme/CMakeLists.txt
Link ClangEnzyme on MacOS otherwise the build fails with a huge wall of errors.
> Link ClangEnzyme on MacOS

- enzyme/Enzyme/ActivityAnalysis.cpp
- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
- enzyme/test/Enzyme/copysign.ll
The funny bithack in https://github.com/wsmoses/Enzyme.jl/issues/27 is caused by copysign, handling it here alongside a relevant cassette call in Enzyme.jl should resolve
> Handle copysign

- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/GradientUtils.h
- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
- enzyme/test/Enzyme/cuda.ll
- enzyme/test/Enzyme/sharedmem.ll
These calls get emitted sometimes in later LLVM versions, even with -ffast-math. We should generically support all the variants of libm functions (ideally by raising/lowering to a common form), but this adds a necessary function for now.
> Handle __sqrt_finite & shared memory

- enzyme/Enzyme/CApi.cpp
- enzyme/Enzyme/FunctionUtils.cpp
- enzyme/Enzyme/Utils.h
This should enable the use of the relevant CL flags without needing to be on a custom branch.
> Fix Command line C ABI & introduce primitive malloc coalesing

- enzyme/Enzyme/AdjointGenerator.h
Handle `nvvm.sqrt` inside of the adjoint generator, instead of a custom libdevice function.
> Handle nvvm sqrt within the Adjointgenerator

- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/CApi.cpp
- enzyme/Enzyme/CApi.h
- enzyme/Enzyme/DifferentialUseAnalysis.h
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/EnzymeLogic.h
- enzyme/Enzyme/FunctionUtils.cpp
- enzyme/Enzyme/FunctionUtils.h
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/GradientUtils.h
- enzyme/Enzyme/Utils.h
I've merged the common boolean flags `fwdMode` and `topLevel` into `DerivativeMode mode` since they were often used in combination to convey the current mode throughout Enzyme.
Combining these flags will clean up some ambiguity.
> Refactor top level

- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
Necessary for current LLVM 13 to not fail
> [TypeAnalysis] create GEP with type

- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/GradientUtils.cpp
Amendments made to
- Adjointgenerator
- GradientsUtils
to enable AD of Fortran with FIR infrastructure, where Enzyme has to contend and mitigate missing type informaiton.
> Enable AD of current FIR dialect

- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/GradientUtils.h
`invertPointerM` uses `lookupM`...
> Move Assertions

- enzyme/test/Enzyme/ReverseMode/cbrt.ll
The reverse mode cbrt.ll test is currently failing on macOS due to different instruction ordering.
> Fix cbrt test on macOS

- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/CApi.cpp
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/EnzymeLogic.h
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/GradientUtils.h
- enzyme/Enzyme/Utils.h
- enzyme/test/Enzyme/ReverseMode/splitSize6.ll
- enzyme/test/Enzyme/ReverseMode/splitSize6nofree.ll
- enzyme/test/Enzyme/ReverseMode/splitSize6nofree2.ll
@jedbrown @LeilaGhaffari While ideally Enzyme won't need to allocate any extra memory for your use case, the `enzyme_nofree` added here will allow you to run split mode multiple times on the same tape.
> Simplify argument handling and add enzyme_nofree option

- enzyme/Enzyme/Enzyme.cpp
- enzyme/test/Enzyme/ReverseMode/gradient-struct-ret.ll
- enzyme/test/Integration/ReverseMode/gradient-struct-return.c
When using autodiff to receive all the gradients in a struct,
the return type of `CI` on ARM emited by clang is `%struct.Foo = type { double, double }` instead of `{ double, double }` on x86. This make the following check fail: `if (diffret->getType() == CI->getType())`
To fix this we can just compare the struct layouts as follows: `CIsty->isLayoutIdentical(diffretsty)`.
All other tests  in `check-enzyme` pass on M1.
> Fix gradient struct return on ARM

- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/EnzymeLogic.h
This permits Julia to use its error handling in the case of an unknown derivative
> Custom noderivative found error handler

- enzyme/Enzyme/CApi.cpp
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/GradientUtils.h
Not used internally in Enzyme, but in Enzyme.jl via the C API for arraycopy
> Handle subtransfer of already-looked up shadows

- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
- enzyme/test/TypeAnalysis/gepint.ll
Without strict aliasing on, this rule creates an inconsistent type info for a load of a virtual function pointer
> Fix C++ integration test

- enzyme/Enzyme/ActivityAnalysis.cpp
Referring to the first, getLine example under -O0 builds.
O3 builds still cause a segfault.
> fix #607 for -O0 builds

- enzyme/Enzyme/ActivityAnalysis.cpp
The `@_ZN9__gnu_cxx12__to_xstringINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEET_PFiPT0_mPKS8_P13__va_list_tagEmSB_z`
one seems strange to me, but based on my libstdc++ usage probably ok. 
How about generally getting (slowly) rid of this list by calling 
`std::string llvm::demangle(const std::string &MangledName)`
in `llvm/Demangle/Demangle.h` for every function missing a definition?
If it succeeds we can still match the beginning, but using the demangled name 
it should end up in a shorter comparison list and we should miss less functions. 
I didn't run into a single fn which I couldn't demangle with llvm-c++filt, so I guess it's valid to still panic then.
> Additional C++ IO support

- enzyme/test/Integration/ForwardMode/rosenbrock.cpp
To avoid regressions, as previously discussed.
Adding as a cpp instead of .ll testcase, since it triggered more than one bug.
> Add rosenbrock test

- enzyme/Enzyme/GradientUtils.cpp
Use scalar type instead of vector type for the GlobalVariable initialiser.
> Fix type mismatch in GlobalVariable initialiser in the case of vector mod

- enzyme/Enzyme/CMakeLists.txt
Users might want to use llvm with an older, officially unsupported cmake (see our CI).
In this case we don't want to use the tablegen function from llvm but rather our own replacement which doesn't use the TRANSFORM command.
> handle old cmake with newer llvm

- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/test/Enzyme/ReverseMode/constexpr.ll
llvm's copyFunctionInto won't add constantexpr to the vmap, since It can be shared, similar to constantData.
fixes #721
> fix ConstantExpr handling in CreateAugmentedPrimal

- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/EnzymeLogic.h
- enzyme/Enzyme/GradientUtils.h
- enzyme/test/Enzyme/ReverseMode/cacheErr.ll
Resolves https://github.com/EnzymeAD/Enzyme/issues/827
> Loose Type Analysis for Floating Point Add

- enzyme/Enzyme/MLIR/Implementations/ArithAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Implementations/LLVMAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Implementations/MemRefAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Implementations/SCFAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Interfaces/AutoDiffOpInterface.td
- enzyme/Enzyme/MLIR/Interfaces/GradientUtils.cpp
To stay in line with prevailing literature, I would suggest to rename `ForwardModeAdjoint` to `ForwardModeTangent` for the nascent MLIR version. `Adjoint` is commonly used to describe the reverse-mode, and hence lends itself to confusion.
Examples in literature, see e.g. "Using Automatic Differentiation for Adjoint CFD Code Development" by Giles et al [1], or section 5.1.2 of the MIT gcm documentation on "Reverse or Adjoint Sensitivity" [2]. The forward mode is more colloquially known as "Tangent"-mode [3,4], which would hence be a more intuitive name in my eyes.
[1] https://people.maths.ox.ac.uk/gilesm/files/NA-05-25.pdf
[2] http://mitgcm.org/sealion/online_documents/node174.html
[3] https://pytorch.org/tutorials/intermediate/forward_ad_usage.html
[4] Chapter 3.1 "Forward Propagation of …
> MLIR: Rename ForwardModeAdjoint to ForwardModeTangent

- enzyme/Enzyme/Enzyme.cpp
for future reuse in prob prog. Diff looks a bit wild event though I only extracted that one function.
Also replace some instance of llvm::Optional with std::optional.
https://discourse.llvm.org/t/deprecating-llvm-optional-x-hasvalue-getvalue-getvalueor/63716/38
> Extract handleArguments

- Readme.md
Both projects have moved, so point to their current location.
> update README links to Julia and Rust

- .github/workflows/ccpp.yml
- enzyme/Enzyme/Enzyme.cpp
- enzyme/test/Integration/ForwardMode/customfwd.c
- enzyme/test/Integration/ReverseMode/customalloc.c
- enzyme/test/Integration/ReverseMode/customcombined.c
- enzyme/test/Integration/ReverseMode/customlog1p.c
- enzyme/test/Integration/ReverseMode/err_too_few_args.c
- enzyme/test/Integration/ReverseMode/warn_cache.c
The new pass manager pipeline has fewer available plugin points to inject an optimization pass (enzyme) at its previous location (right before vectorization). This means that existing optimizations will not run before Enzyme on the new pm.
Support for better plugin points has been improving over time (aka adding new plugin injection points). Unfortunately, they aren't available on all LLVM versions. This remedies this, by forcibly running the passes that would've occured in the pipeline before vectorization and after the point Enzyme can be injected in the New PM. As new LLVM's have more plugin point options, this manual list diminishes over LLVM version time.
> New PM clang

- enzyme/Enzyme/MLIR/Implementations/ArithAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Implementations/MemRefAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Implementations/SCFAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Interfaces/EnzymeLogic.h
- enzyme/Enzyme/MLIR/Interfaces/EnzymeLogicReverse.cpp
- enzyme/Enzyme/MLIR/Interfaces/GradientUtilsReverse.cpp
- enzyme/Enzyme/MLIR/Interfaces/GradientUtilsReverse.h
- enzyme/test/MLIR/CMakeLists.txt
- enzyme/test/MLIR/ReverseMode/CMakeLists.txt
- enzyme/test/MLIR/ReverseMode/bbarg-order.mlir
- enzyme/test/MLIR/ReverseMode/pow.mlir
Per the weekly Enzyme-MLIR meeting today, this PR should include all the fixes that are currently in the [reverse mode fork](https://github.com/EnzymeAD/Enzyme-MLIR-Reverse).
Specifically:
- Bugfixes/cleanup around the internal differential value mapping
- Bugfix around `scf.for`
- Reverse mode implementation for `memref.subview`
@umatin Feel free to let me know if I missed anything.
> Bugfixes around scf.for + memref.subview implementation

- .devcontainer/devcontainer.json
Bazel BUILD file prevents docker from mounting the build directory. Changed location of build directory.
> Fix devcontainer

- enzyme/Enzyme/ActivityAnalysis.cpp
- enzyme/Enzyme/ActivityAnalysis.h
- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/CApi.cpp
- enzyme/Enzyme/CacheUtility.cpp
- enzyme/Enzyme/CacheUtility.h
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/GradientUtils.h
- enzyme/Enzyme/InstructionBatcher.cpp
- enzyme/Enzyme/LibraryFuncs.h
- enzyme/Enzyme/PreserveNVVM.cpp
- enzyme/Enzyme/TypeAnalysis/RustDebugInfo.cpp
- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.h
- enzyme/Enzyme/Utils.h
`std::map<std::string, T> `--> `StringMap<T>`
`std::set<std::string>` --> `StringSet<>`
Additionally replace `std::string` in function signatures with `StringRef` and avoid materialising `std::strings` where possible
> Fix string usage

- enzyme/Enzyme/AdjointGenerator.h
- enzyme/tools/enzyme-tblgen/caching.cpp
Creating the IRBuilder from a BasicBlock causes us to loose debug info for the original instruction
> Fix missing debug info

- enzyme/Enzyme/CApi.cpp
LLVM copy with an empty list copies all metadata, rather than none.
> Fix empty metadata copy

- enzyme/tools/enzyme-tblgen/blasDiffUseUpdater.h
Apparently you can introduce subtle bugs if you re-do work unnecessarily.
@wsmoses this new behavior should be always correct, right?
```
27   if (val == arg_lda && need_lda && !cache_lda)
26      return true;
```
At least it will fix the lda issue for runtime-activity. Adding some more tests there rn.
> simplify and fix blasDiffUse

- enzyme/BCLoad/CMakeLists.txt
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/test/Enzyme/ForwardMode/Faddeeva_erf_aarch64.ll
- enzyme/test/Enzyme/ReverseMode/Faddeeva_erf_aarch64.ll
- enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp
> enzyme-tblgen fix for aarch64 CFP

- enzyme/Enzyme/Utils.cpp
- enzyme/test/Enzyme/ReverseMode/blas/gemv_c_loop2.ll
- enzyme/test/Enzyme/ReverseMode/blas/gemv_c_loop3_matcopy.ll
If c feels like passing characters as 32 bit integers, we should let c do how it feels.
With this fix, I can differentiate the actual c example, link against openblas, and run it, without crashing. Jay.
@wsmoses The matrixcopy looks suspicious.
> fix transpose handling for 32 bit characters

- enzyme/Enzyme/ActivityAnalysis.cpp
- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/CMakeLists.txt
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/test/Integration/ForwardMode/fwdandrev.cpp
- enzyme/test/Integration/ForwardMode/nofn.cpp
- enzyme/test/Integration/ForwardMode/rosenbrock.cpp
- enzyme/test/Integration/ForwardMode/rwrloop.c
- enzyme/test/Integration/ForwardMode/test_utils.h
- enzyme/test/Integration/ReverseMode/MSinput.ll
- enzyme/test/Integration/ReverseMode/allocatedtape.c
- enzyme/test/Integration/ReverseMode/allocatedtape_err.c
- enzyme/test/Integration/ReverseMode/cmplx.cpp
- enzyme/test/Integration/ReverseMode/map.cpp
- enzyme/test/Integration/ReverseMode/metarwr.c
- enzyme/test/Integration/ReverseMode/omp3.c
- enzyme/test/Integration/ReverseMode/perturbation.cpp
- enzyme/test/Integration/ReverseMode/remat.c
- enzyme/test/Integration/ReverseMode/rwrloop.c
- enzyme/test/Integration/ReverseMode/test_utils.h
- enzyme/test/Integration/ReverseMode/virtualshadow3.cpp
~~How do you feel about in Enzyme.cpp replacing all of the
`metaString->startswith("enzyme_")`
by
`metaString->contains("enzyme_")`
?
These can be mangled too.~~
> support more names from MS

- enzyme/Enzyme/AdjointGenerator.h
@swilliamson7 this is a fix for that memset assertion error that shouldn't have happened, we were discussing yesterday
> Fix julia memset runtime err

- enzyme/Enzyme/CacheUtility.cpp
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/GradientUtils.h
- enzyme/test/Enzyme/ReverseMode/multiloopexit.ll
Previously, Enzyme assumed that an exit block could have only had one loop which exited into it. This is not the case for code such as:
```c
for(...) {
for (...) {
if (shoudlExit)
goto metabreak;
}
}
metabreak:;
```
This fixes this
cc @tthsqe12
> Fix use of exit block shared by multiple loops

- enzyme/Enzyme/InstructionDerivatives.td
- enzyme/test/Enzyme/ReverseMode/expm1f.ll
This pull request adds instructions in InstructionDerivatives.td for the single-precision and long double versions of expm1 in the standard math library of C++. It also adds a test for expm1f to the reverse mode test directory.
> Adding instructions for expm1f / expm1l

- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/CApi.cpp
- enzyme/Enzyme/CApi.h
- enzyme/Enzyme/DiffeGradientUtils.cpp
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/EnzymeLogic.h
- enzyme/Enzyme/FunctionUtils.cpp
- enzyme/Enzyme/FunctionUtils.h
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/GradientUtils.h
- enzyme/Enzyme/InstructionBatcher.cpp
- enzyme/Enzyme/TraceGenerator.cpp
- enzyme/Enzyme/TraceUtils.cpp
- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
- enzyme/test/Integration/ForwardMode/err_empty.c
- enzyme/test/Integration/ReverseMode/err_empty.c
Also exposed batch in the CAPI and added some docs while at it.
This also notably means that:
1) the compiler won't crash if there's a non differentiable function it doesn't know about
2) it provides nice error messages at the source line location/backtrace of the call that caused it
3) it does so for all errors/functions at once (rather than doing one crash at a time)
> Nice error message for undifferentiable functions

- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/DiffeGradientUtils.cpp
- enzyme/Enzyme/Utils.cpp
- enzyme/test/Enzyme/ReverseMode/blas/gemm_f_c_lacpy_runtime_act.ll
- enzyme/test/Enzyme/ReverseMode/blas/gemv_f_c_split_blascpy.ll
- enzyme/test/Enzyme/ReverseMode/blas/spmv_f_c_lacpy.ll
- enzyme/test/Integration/ReverseMode/blas_gemm.c
- enzyme/test/Integration/blas_inline.h
- enzyme/tools/enzyme-tblgen/blas-tblgen.cpp
We were allocating the temporary in the forward pass, before we had set byref_m, and byref_n -> the temporary allocation size was undef -> lots of errors.
Also now we deallocate things properly.
> [Blas] fix temporary allocation (and deallocation)

- enzyme/Enzyme/FunctionUtils.cpp
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/test/Integration/Sparse/ringspring.cpp
This PR is a slight change to the simplified springs example that changes the topology of the springs so that is a ring of 1D springs rather than a line of springs. Executing this code produced the following result on my machine:
```row=0 col=7 val=nan
Assertion failed: (abs(val) > 0.00001), function inner_store, file new_sparse.cpp, line 68.
[1]    24375 abort      ./new_sparse.out
```
> Ring of springs integration test using modulo

- enzyme/Enzyme/ActivityAnalysis.cpp
- enzyme/Enzyme/ActivityAnalysis.h
This flag disables the behaviour for activity analysis to re-evaluate instructions or values when new information is added. This introduces a potential tradeoff between the time spent in analysis and the precision of the analysis results.
> Add flag to disable recursive activity analysis

- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
- enzyme/test/TypeAnalysis/numargmismatch.ll
Fixes https://github.com/EnzymeAD/Enzyme/issues/728
> [TypeAnalysis] handle arg count mismatch

- enzyme/BCLoad/BCLoader.cpp
- enzyme/Enzyme/ActivityAnalysis.cpp
- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/CallDerivatives.cpp
- enzyme/Enzyme/Clang/EnzymeClang.cpp
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/FunctionUtils.cpp
- enzyme/Enzyme/FunctionUtils.h
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/MLIR/Analysis/ActivityAnalysis.cpp
- enzyme/Enzyme/PreserveNVVM.cpp
- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.h
- enzyme/Enzyme/Utils.h
- enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp
https://github.com/llvm/llvm-project/commit/5ac12951b4e9bbfcc5791282d0961ec2b65575e9 deprecated the use of `StringRef::startswith` and `StringRef::endswith` in favor of `starts_with` and `ends_with`. Introduce a helper and update all uses in Enzyme codebase.
> move away from using deprecated StringRef API

- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
Cast the type of ConstantInt to `IntegerType`. This should be backwards-compatible.
> update TypeAnalysis for recent LLVMs

- enzyme/Enzyme/MLIR/Analysis/AliasAnalysis.cpp
- enzyme/Enzyme/MLIR/Analysis/AliasAnalysis.h
- enzyme/Enzyme/MLIR/Analysis/DataFlowActivityAnalysis.cpp
- enzyme/test/MLIR/ActivityAnalysis/allocator.mlir
- enzyme/test/MLIR/ActivityAnalysis/allocret.mlir
- enzyme/test/MLIR/ActivityAnalysis/memalgn.mlir
- enzyme/test/MLIR/ActivityAnalysis/multiptr.mlir
- enzyme/test/MLIR/ActivityAnalysis/string.mlir
- enzyme/test/MLIR/ActivityAnalysis/subld.mlir
- enzyme/test/MLIR/AliasAnalysis/func_attributes.mlir
- enzyme/test/MLIR/AliasAnalysis/llvm_casts.mlir
Also add conservative handling of unknown situations in alias analysis.
> [mlir] support unknown (top) state in aliasing and activity analysis

- enzyme/Enzyme/MLIR/Analysis/AliasAnalysis.cpp
- enzyme/Enzyme/MLIR/Analysis/DataFlowActivityAnalysis.cpp
This requires injecting ModRef information about library functions.
Depends on #1570.
> [mlir] correctly handle "unknown" state in activity analysis

- enzyme/BUILD
- enzyme/Enzyme/MLIR/Analysis/ActivityAnalysis.cpp
- enzyme/Enzyme/MLIR/Analysis/DataFlowActivityAnalysis.cpp
- enzyme/Enzyme/MLIR/Implementations/ArithDerivatives.td
- enzyme/Enzyme/MLIR/Implementations/CMakeLists.txt
- enzyme/Enzyme/MLIR/Implementations/Common.td
- enzyme/Enzyme/MLIR/Implementations/CoreDialectsAutoDiffImplementations.h
- enzyme/Enzyme/MLIR/Implementations/LLVMAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Implementations/LLVMDerivatives.td
- enzyme/Enzyme/MLIR/Implementations/NVVMAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Implementations/NVVMDerivatives.td
- enzyme/Enzyme/MLIR/Implementations/SCFAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Interfaces/AutoDiffOpInterface.td
- enzyme/Enzyme/MLIR/enzymemlir-opt.cpp
- enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp
I'm not sure what the right way is to integrate this into dataflow activity analysis
> [MLIR][ActivityAnalysis] create activity interface

- enzyme/Enzyme/TypeAnalysis/TypeTree.h
Fixes https://github.com/EnzymeAD/Enzyme/issues/1743
> TypeTree speedup shiftindicies

- .github/dependabot.yml
Let dependabot update our actions and fix all those deprecation warnings, so I don't have to
> Enable Dependabot for Github actions

- .github/workflows/enzyme-mlir.yml
- enzyme/Enzyme/MLIR/Implementations/LinalgAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Passes/AddToOpToIndexAndLoad.cpp
- enzyme/Enzyme/MLIR/Passes/AddToOpToSplit.cpp
- enzyme/Enzyme/MLIR/Passes/EnzymeMLIRPass.cpp
- enzyme/Enzyme/MLIR/Passes/ShadowedGradientToCache.cpp
Remove most uses of `ConversionPatternRewriter` that were spurious anyway. Update one use to use `IRRewriter` instead since the conversion rewriter should no longer be used directly. Clean up includes accordingly.
> Update MLIR to 2c9b6c1b36b8185299de083c3058e0c1e7760442

- enzyme/Enzyme/MLIR/Passes/AddToOpToIndexAndLoad.cpp
- enzyme/Enzyme/MLIR/Passes/Passes.h
Includes a real memory problem: ValueRange is a non-owning container, assining the returned value of type SmallVector<Value> to ValueRange will lead to ValueRange starting with a dangling pointer.
> Fix clang-tidy findings

- enzyme/Enzyme/InstructionDerivatives.td
- enzyme/Enzyme/MLIR/Analysis/CMakeLists.txt
- enzyme/Enzyme/MLIR/Analysis/DataFlowActivityAnalysis.cpp
- enzyme/Enzyme/MLIR/Analysis/DataFlowAliasAnalysis.cpp
- enzyme/Enzyme/MLIR/Analysis/DataFlowAliasAnalysis.h
- enzyme/Enzyme/MLIR/Passes/PrintAliasAnalysis.cpp
- enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp
Macos Bazel build didn't like us calling something AliasAnalysis.h and MLIR also having the same leading to nonsense issues that was strictly easier for us to rename to DataFlowAliasAnalysis anyways
> Fix bazel build for macos

- enzyme/Enzyme/MLIR/Analysis/CMakeLists.txt
- enzyme/Enzyme/MLIR/Analysis/DataFlowActivityAnalysis.cpp
- enzyme/Enzyme/MLIR/Analysis/DataFlowAliasAnalysis.cpp
- enzyme/Enzyme/MLIR/Analysis/DataFlowAliasAnalysis.h
- enzyme/Enzyme/MLIR/Analysis/DataFlowLattice.cpp
- enzyme/Enzyme/MLIR/Analysis/DataFlowLattice.h
- enzyme/Enzyme/MLIR/Passes/PrintAliasAnalysis.cpp
For context, the conceptual `AliasClassSet`, `AliasClassLattice`, and `PointsToSets` data structures were immensely useful in implementing activity annotations. The "`lattice of sets that might be undefined or unknown`" and "`map of attributes to those sets`" are exactly the kind of data structures that activity annotations uses to propagate these relative "origins" both forward and backward, in an intraprocedural analysis.
This PR aims to be an intermediate step towards merging in activity annotations by breaking out the re-usable logic into abstract classes.
> [mlir] Define generic set/map lattices for dataflow analyses

- enzyme/Enzyme/Clang/include_utils.td
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/EnzymeLogic.h
- enzyme/test/Enzyme/Truncate/cmp.ll
- enzyme/test/Enzyme/Truncate/const.ll
- enzyme/test/Enzyme/Truncate/intrinsic.ll
- enzyme/test/Enzyme/Truncate/select.ll
- enzyme/test/Enzyme/Truncate/simple.ll
- enzyme/test/Enzyme/Truncate/value.ll
- enzyme/test/Integration/Truncate/simple.cpp
- enzyme/test/Integration/Truncate/truncate-all.cpp
This allows all floating point numbers of a given precision to be replaced with a custom representation on which we can perform arbitrary computation at each original fp operation.
> Memory truncation mode

- enzyme/Enzyme/CallDerivatives.cpp
Forward mode `MPI_Reduce` was doomed to assertion failures.
> FIx `MPI_Reduce` for forward mode

- enzyme/Enzyme/TypeAnalysis/ConcreteType.h
LLVM's in-tree use was mostly migrated in https://github.com/llvm/llvm-project/commit/3f18f7c0072b642f5fe88d2fb7bb8ccf69a6c6f5. This will prevent breakages if/when that macro is deleted.
> Replace `LLVM_FALLTHROUGH` with `[[fallthrough]]`

- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/test/Enzyme/ReverseMode/fprintf.ll
Noticed this when trying to run LULESH with `__enzyme_autodiff`. When compiling the following example with a `fprintf`, I got an error:`Enzyme: No create nofree of empty function (fprintf) fprintf) at context:   %3 = call i32 (%struct.__sFILE*, i8*, ...) @fprintf(%struct.__sFILE* noundef %2, i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str, i64 0, i64 0)) #4 (fprintf)
`.
```cpp
#include <cstdio>
extern double __enzyme_autodiff(void*, double);
double fn(double vec) {
fprintf(stderr, "test");
return vec * vec;
}
int main() {
double x = 2.1;
__enzyme_autodiff((void*)fn, x);
}
```
Not sure if this is the best fix, though!
> Handle fprintf in handleKnownCallDerivatives

- enzyme/CMakeLists.txt
If we provide a path, we want Enzyme to actually use it.
If that's not possible, rather error than taking a surprising other version.
closes #1815
> abort compilation if cfg not found

- enzyme/BUILD
> Fix bazel to include "complex-derivatives" rule

- enzyme/Enzyme/ActivityAnalysis.cpp
Attemping to add __cxa_thread_atexit_impl.
We ran into an issue using enzyme and we got this error message, we're not sure if the line-change will fix it.
```
error: <unknown>:0:0: in function preprocess__ZN3std3sys6common12thread_local10fast_local12Key$LT$T$GT$14try_initialize17h538e209caf245dc5E.llvm.5507895982844929938 ptr (ptr, ptr): Enzyme: cannot compute with global variable that doesn't have marked shadow global
@__cxa_thread_atexit_impl = extern_weak global i8
```
> Adding __cxa_thread_atexit_impl

- enzyme/Enzyme/CacheUtility.cpp
- enzyme/Enzyme/DiffeGradientUtils.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/SCEV/ScalarEvolutionExpander11.cpp
- enzyme/Enzyme/Utils.cpp
- added  missing moves
- we don't want to use `emplace_back` if its not needed since it introduces compile time overhead due to templating
> Fix usage of emplace_back

- enzyme/Enzyme/MLIR/Analysis/DataFlowAliasAnalysis.cpp
- enzyme/Enzyme/MLIR/Analysis/DataFlowAliasAnalysis.h
- enzyme/Enzyme/MLIR/Dialect/Dialect.td
- enzyme/Enzyme/MLIR/Dialect/EnzymeOps.td
- enzyme/Enzyme/MLIR/Passes/Passes.td
Add a mode for pointer analysis to operate in "relative" mode, operating on each function intra-procedurally starting with leaf nodes on the function call graph and serializing function summaries that are used when analyzing their call sites.
> [mlir] Function summary-based pointer analysis

- enzyme/Enzyme/ActivityAnalysis.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/test/Enzyme/ReverseMode/rust-eprintln.ll
Looks like during (manual) upstreaming I added it to the wrong NoFree list, so my test was still not passing after updating the Enzyme submodule. This one should be the right noFree list.
> use correct NoFree list

- enzyme/Enzyme/ActivityAnalysis.cpp
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
- enzyme/Enzyme/MLIR/Analysis/ActivityAnalysis.cpp
- enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
- enzyme/Enzyme/Utils.h
In C, single-char `fprintf`'s such as `fprintf(stdout, "\n");` are optimized to `fputc("\n", stdout);` for `-O{1-3}` (technically the `\n` would really be a single system-dependent character being interpreted as a newline, this example is for ease of comparison). Thus, code such as the following:
```C
// main.c
#include <stdlib.h>
#include <stdio.h>
extern double __enzyme_autodiff(void*, ...);
int enzyme_const, enzyme_dup, enzyme_out;
double calc(int n, double *x)
{
fprintf(stdout, "hello world!"); // this is handled correctly
fprintf(stdout, "\n"); // this gets optimized to `fputc` for O{1-3} and causes the error
return 0.0;
}
int main()
{
int n = 12;
double *x = (double *)malloc((size_t)n * sizeof(double));
double *grad = (double *)malloc((size_t)n * sizeof(double));
for (int i = 0; i < …
```
> Extended analysis to ignore fputc

- enzyme/Enzyme/AdjointGenerator.h
- enzyme/Enzyme/Clang/EnzymeClang.cpp
- enzyme/Enzyme/EnzymeLogic.cpp
I built this repository for the first time today and whilst doing so noticed a few warnings (on `clang-18`). I tidied up the ones that looked fairly simple in order to get cleaner build output locally, so thought I'd raise the changes.
> Fix unused field and override warnings

- enzyme/Enzyme/AdjointGenerator.h
Since the v0.0.150, it is not possible to compile Enzyme with clang. The source of the issue is a loop over references (local binding) that contains a lambda function. https://github.com/EnzymeAD/Enzyme/pull/2079/files#diff-ab7735609ebf1b75b3d6baedc231689532dff0a7a8e4e1838c3aed11c99795e5R3111
Clang refuses to compile it because local binding are not variables and cannot be captured by the lambda function. Solution here is to create a variable that can be then captured by the lambda function.
https://stackoverflow.com/questions/50799719/reference-to-local-binding-declared-in-enclosing-function?noredirect=1&lq=1
> Fix clang compilation (failing since 0.0.150)

- enzyme/Enzyme/MLIR/Interfaces/GradientUtils.cpp
The build for the latest LLVM bump appeared to break the MLIR build due to member variables being initialized in a different order than they were declared.
> [mlir] Fix build for LLVM 20

- enzyme/Enzyme/MLIR/Implementations/FuncAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/enzymemlir-opt.cpp
- enzyme/test/MLIR/ReverseMode/func.mlir
prompted by https://github.com/EnzymeAD/Reactant.jl/pull/171#issuecomment-2420942682.
We can now run enzyme-batch -> enzyme-wrap without inlining.
```mlir
// ./bazel-bin/enzymexlamlir-opt test/lit_tests/batchtests/autodiff.mlir --enzyme-batch --enzyme-wrap="infn=main retTys=enzyme_active argTys=enzyme_active mode=ReverseModeCombined" --canonicalize --remove-unnecessary-enzyme-ops --arith-raise --cse --canonicalize --arith-raise --enzyme-simplify-math --mlir-print-ir-before=enzyme-batch
// -----// IR Dump Before BatchPass (enzyme-batch) //----- //
module {
func.func @f(%arg0: tensor<f32>) -> tensor<f32> {
%0 = stablehlo.multiply %arg0, %arg0 : tensor<f32>
return %0 : tensor<f32>
}
func.func @main(%arg0: tensor<10xf32>) -> tensor<10xf32> {
%0 = enzyme.batch @f(%arg0) {batch_shape = …
```
> mlir: Func call reverse diff

- enzyme/Enzyme/MLIR/Implementations/ArithAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Interfaces/AutoDiffOpInterface.td
- enzyme/Enzyme/MLIR/Interfaces/CloneFunction.cpp
- enzyme/Enzyme/MLIR/Interfaces/CloneFunction.h
- enzyme/Enzyme/MLIR/Passes/EnzymeBatchPass.cpp
This PR modifies the `BatchOpInterface` to enable generating multiple operations and then map from the original results to new values. To do this, `batchSizes` support is removed in the original Enzyme MLIR cloning and batch cloning is implemented on its own.
See https://github.com/EnzymeAD/Enzyme-JAX/pull/149#issuecomment-2450019084 for more context.
> mlir: Modify `BatchOpInterface` to allow generating more than one operation

- enzyme/tools/enzyme-tblgen/blas-tblgen.h
- enzyme/tools/enzyme-tblgen/blasDeclUpdater.h
- enzyme/tools/enzyme-tblgen/blasDiffUseUpdater.h
- enzyme/tools/enzyme-tblgen/blasTAUpdater.h
Adds a few more missing header guards and marks some functions implemented in headers as `inline`.
> Marks functions inline in BLAS tblgen

- .gitignore
- enzyme/CMakeLists.txt
- enzyme/CMakePresets.json
Adds CMake presets that have parity with the existing configuration. This will hopefully make it easier for people to extend/customize Enzyme builds on their platform.
No real changes to the build system are expected because the presets mirror the existing configuration. It's hopefully something that can be refined and extended in future, but works fine for the sake of an initial PR to make it available for basic builds.
Closes #2162
> Adds initial CMake presets configuration

- enzyme/Enzyme/MLIR/Implementations/Common.td
- enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp
this removes ConjIfComplex which seems unused and can be implemented in terms of SelectIfComplex
> tblgen: Implement SelectIfComplex

- Readme.md
I just finished up merging Enzyme into nixpkgs, so I thought a mention in the README might be useful
https://search.nixos.org/packages?channel=unstable&show=enzyme&from=0&size=50&sort=relevance&type=packages&query=enzyme
Like spack, nix is really handy for deterministic builds and setting up ephemeral dev environments with all the dependencies baked in.
For example, with nix you can do something like
```nix
(
system: let
pkgs = import nixpkgs {inherit system;};
buildInputs = with pkgs; [enzyme cmake llvmPackages.bintools];
in
with pkgs; {
devShells.default = mkShell.override {stdenv = clangStdenv;} {
inherit buildInputs;
};
}
);
```
and prepare an environment with everything you need already built and linked together to develop with Enzyme!
> Add nixpkgs to README

- enzyme/CMakePresets.json
The Intel compilers are LLVM based and somewhat commonly used for HPC applications so I think presets for them are potentially useful to someone building everything from source. I was on the fence about GCC but it is used in some of the CI workflows and using its tooling/analysis of the Enzyme source code doesn't seem completely redundant, therefore I added those also.
Includes a tiny improvement to move configuration specific compiler flag cache variables to their respective configuration's preset, which reduces CMake warnings about unused cache variables.
> Adds Intel oneAPI and GCC Linux CMake presets

- enzyme/Enzyme/MLIR/Implementations/BuiltinAutoDiffTypeInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Implementations/SCFAutoDiffOpInterfaceImpl.cpp
- enzyme/Enzyme/MLIR/Interfaces/AutoDiffOpInterface.h
- enzyme/Enzyme/MLIR/Interfaces/AutoDiffOpInterface.td
- enzyme/Enzyme/MLIR/Interfaces/AutoDiffTypeInterface.td
- enzyme/Enzyme/MLIR/Passes/Passes.h
- enzyme/Enzyme/MLIR/Passes/Passes.td
- enzyme/Enzyme/MLIR/Passes/RemovalUtils.cpp
- enzyme/Enzyme/MLIR/Passes/RemovalUtils.h
- enzyme/Enzyme/MLIR/Passes/RemoveUnusedEnzymeOps.cpp
- enzyme/Enzyme/MLIR/enzymemlir-opt.cpp
- enzyme/test/MLIR/ReverseMode/pow.mlir
- enzyme/test/MLIR/ReverseMode/scf_for.mlir
> mlir: Add Enzyme ops removal on structured control flow

- .github/workflows/enzyme-mlir.yml
- enzyme/Enzyme/MLIR/Passes/CMakeLists.txt
- enzyme/Enzyme/MLIR/Passes/EnzymeMLIRPass.cpp
- enzyme/Enzyme/MLIR/Passes/Passes.td
- enzyme/Enzyme/MLIR/Passes/RemovalUtils.cpp
- enzyme/Enzyme/MLIR/Passes/RemovalUtils.h
- enzyme/Enzyme/MLIR/Passes/RemoveUnusedEnzymeOps.cpp
- enzyme/test/MLIR/ForwardMode/batched_scalar.mlir
- enzyme/test/MLIR/ReverseMode/batched_square.mlir
- enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp
In trying to get a simple reverse test to work I noticed the broadcastOp insertion was in the wrong place. Now it works.
BroadcastOp does not participate in CSE yet, though.
> Batched reverse mode

- enzyme/Enzyme/InstructionDerivatives.td
- enzyme/Enzyme/MLIR/Implementations/Common.td
- enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp
cc @mofeing, we can collaborate to integrate in your fft pr.
I am open to other naming ideas.
> tablegen: Add StaticSelect to select based on static condition

- enzyme/Enzyme/CApi.cpp
- enzyme/Enzyme/CApi.h
- adds EnzymeRegisterCallHandler and EnzymeGradientUtilsNewFromOriginal to C API header
- const qualify arg to make it easier to use from rust
Reduced version of #2223
> add EnzymeRegisterCallHandler to C API header 

- enzyme/Enzyme/MLIR/Implementations/Common.td
- enzyme/Enzyme/MLIR/Interfaces/EnzymeLogic.h
- enzyme/Enzyme/MLIR/Interfaces/EnzymeLogicReverse.cpp
- enzyme/Enzyme/MLIR/Interfaces/GradientUtilsReverse.cpp
- enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp
> WIP variadic

- enzyme/Enzyme/ActivityAnalysis.cpp
Seen in #2235  / https://github.com/ECP-WarpX/impactx/pull/825
```
error: Enzyme: No augmented forward pass found for
```
Per discussion in #2235: Should this also go in another list?
> `strcpy` to Known Inactive Functions

- enzyme/Enzyme/PreserveNVVM.cpp
@wsmoses  This is to fix the defect reported in [here ](https://github.com/EnzymeAD/Enzyme/issues/2053): the custom gradient for cuda device code give the error of 
`__enzyme_register_gradient must be a constant aggregate @__enzyme_register_gradient_AtomicAdd = internal global [3 x ptr] undef, align 16
`
> fix-cuda-custom-gradient

- enzyme/Enzyme/CMakeLists.txt
- enzyme/Enzyme/Enzyme.cpp
I noticed that the ENZYME_RUNPASS variable is ignored, when you just pass it as `-DENZYME_RUNPASS` to cmake.
This might also affect your `BUILD` file, idk.
With these changes it now does run the augmentedPassBuilder.
> recognizing ENZYME_RUNPASS for lib/LLVM Enzyme builds

- enzyme/Enzyme/Utils.h
@wsmoses While trying to remove the plugin dependency I ran into this issue.
```
running: cd "/home/manuel/prog/rust-new/build/x86_64-unknown-linux-gnu/enzyme/build" && CMAKE_PREFIX_PATH="" DESTDIR="" LLVM_CONFIG_REAL="/home/manuel/prog/rust-new/build/x86_64-unknown-linux-gnu/llvm/bin/llvm-config" "cmake" "/home/manuel/prog/rust-new/src/tools/enzyme/enzyme/" "-G" "Ninja" "-DCMAKE_INSTALL_MESSAGE=LAZY" "-DCMAKE_C_COMPILER=cc" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_ASM_COMPILER=cc" "-DCMAKE_C_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64 --target=x86_64-unknown-linux-gnu" "-DCMAKE_CXX_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64 --target=x86_64-unknown-linux-gnu" "-DCMAKE_SHARED_LINKER_FLAGS=" "-DCMAKE_MODULE_LINKER_FLAGS=" "-DCMAKE_EXE_LINKER_FLAGS=" …
```
> fix the enzyme to work again with rust and llvm 20

- enzyme/Enzyme/TypeAnalysis/TypeTree.h
When looking into https://github.com/EnzymeAD/Enzyme.jl/issues/2317 the issue seemed to be that `minIndices.size() == 0` and thus this assignment does fail.
> Avoid seqfault of minIndicies.size() == 0

- enzyme/Enzyme/PreserveNVVM.cpp
- enzyme/Enzyme/Utils.cpp
- enzyme/Enzyme/Utils.h
We no longer need to parse the string triple.
> update for llvm::Triple becoming a proper class

- enzyme/Enzyme/InstructionDerivatives.td
fix: add support for LLVM 19 trigonometric function intrinsics
Add patterns for automatic differentiation of acos, atan, and asin functions
using LLVM 19's new intrinsics. This fixes the compilation error when using
__enzyme_autodiff with these trigonometric functions.
The implementation follows the mathematical derivatives:
- acos: -1/√(1-x²)
- atan: 1/(1+x²)
- asin: 1/√(1-x²)
Fixes #2243
> support for LLVM 19

- enzyme/Enzyme/MLIR/Passes/RemoveUnusedEnzymeOps.cpp
Useful to get error messages following https://github.com/EnzymeAD/Enzyme-JAX/pull/861.
> Report diagnostic as errors in ops removal interface

- enzyme/Enzyme/CMakeLists.txt
Upstreaming of https://github.com/rust-lang/enzyme/pull/4
Incorrect guard caused a build failure in https://github.com/rust-lang/rust/pull/140064#issuecomment-2836408078
(There might be another fix needed, but this seems uncontroversial?)
> don't access LLVMEnzyme on apple builds if LLVM_PLUGINS isn't set

- enzyme/BCLoad/CMakeLists.txt
This (in combination with yesterdays fix) let's me build rustc on apple.
Without this fix I get
```
-- BCPass-20 ignored -- Loadable modules not supported on this platform.
CMake Error at BCLoad/CMakeLists.txt:108 (target_include_directories):
target_include_directories called with non-compilable target type
```
Used rust commands
`./configure --enable-llvm-link-shared --enable-llvm-enzyme --release-channel=nightly --enable-llvm-assertions --enable-clang --enable-lld --enable-option-checking --enable-ninja --disable-docs`
Not used flag: ` --enable-llvm-plugins `
I don't know under which flags exactly we should disable it.
if APPLE AND NO_PLUGINS?
> fix apple builds against a no-plugin LLVM

- enzyme/Enzyme/CApi.cpp
- enzyme/Enzyme/CApi.h
- enzyme/Enzyme/TypeAnalysis/TypeAnalysisPrinter.cpp
This PR introduces a C API to dynamically set the type-analysis-func flag (FunctionToAnalyze).
- Added: EnzymeSetCLString(void* ptr, const char* val) to CApi.cpp and CApi.h
- This enables users to set string-based LLVM command-line options at runtime.
> Add C API for setting type-analysis-func via EnzymeSetCLString

- enzyme/Enzyme/ActivityAnalysis.cpp
- enzyme/Enzyme/CallDerivatives.cpp
- enzyme/Enzyme/DifferentialUseAnalysis.h
- enzyme/Enzyme/Enzyme.cpp
- enzyme/Enzyme/GradientUtils.cpp
- enzyme/Enzyme/Utils.h
- enzyme/test/Enzyme/ReverseMode/ignore_derivatives.ll
The goal is to provide a function `y = ignore_derivative(x)` that will detach uses of `y` from the derivative calculations for `x`
x-ref: https://github.com/EnzymeAD/Enzyme.jl/pull/2479#issuecomment-3089738818
> Introduce __enzyme_ignore_derivatives

- enzyme/Enzyme/ActivityAnalysis.cpp
This fixes errors encountered when attempting to build a [library](https://github.com/ORNL/GridKit/issues/141) with Enzyme and an undefined behavior sanitizer, e.g., `Enzyme: No forward mode derivative found for __ubsan_handle_type_mismatch_v1`. 
Adding the flagged functions to `KnownInactiveFunctions` is a step in the right direction, though there are other errors that popped up for our use case, and will be addressed at a later time.
CC @wsmoses @pelesh
> Add ubsan functions to KnownInactiveFunctions

- enzyme/Enzyme/MLIR/Dialect/Ops.cpp
- enzyme/test/MLIR/ForwardMode/canonicalize.mlir
> [MLIR] Forward Mode arg conversion for dup -> const

- enzyme/Enzyme/CApi.cpp
- enzyme/Enzyme/CApi.h
- enzyme/Enzyme/Utils.h
- enzyme/test/Enzyme/ForwardMode/fp128.ll
- enzyme/test/Enzyme/ReverseMode/fp128.ll
This PR adds support for `fp128` (128-bit quad-precision floating-point) types in Enzyme, following the existing pattern used for
`x86_fp80` support.
While adding fp128 support, I noticed that `IntToFloatTy()` was missing the case for converting 80-bit integers to `x86_fp80`, even
though the reverse function `FloatToIntTy()` already supported it. This has been fixed as well.
Does this make sense? The case 80 addition is correct and should be kept.
> support for f128

- .github/workflows/tagger.yml
[`tibdex/github-app-token`](https://github.com/tibdex/github-app-token) is now archived in favour of [`actions/create-github-app-token`](https://github.com/actions/create-github-app-token).
> [CI] Replace `tibdex/github-app-token` with `actions/create-github-app-token`

- .github/workflows/enzyme-julia.yml
Updated actions versions and added color output for Julia commands.  Ref: https://github.com/EnzymeAD/Enzyme.jl/pull/2601#issuecomment-3316162370.
> [CI] Upgrade GitHub Actions and use `default` architecture
