EnzymeAD/Enzyme

enzyme/Enzyme/Enzyme.cpp

This needs to return for Enzyme.jl to be happy (and yes we'll need to rebuild the binaries).

Restore exported C symbol

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/test/Enzyme/enzyme_inactive.ll
enzyme/test/Enzyme/enzyme_inactive2.ll

This should make it easier for frontends like Enzyme.jl to integrate constructs.

Custom Enzyme inactive marker

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/Enzyme/GradientUtils.cpp

Enable correct global activity analysis

---

Readme.md

Enzyme was accepted for packaging in Homebrew at https://github.com/Homebrew/homebrew-core/pull/72873.

Update Readme installation instructions

---

content/Installation/_index.md

Add Homebrew installation instructions to website

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/CApi.cpp
enzyme/Enzyme/CApi.h
enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/EnzymeLogic.h
enzyme/Enzyme/FunctionUtils.cpp
enzyme/Enzyme/FunctionUtils.h
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.h
enzyme/test/Integration/eigentensorreal.cpp
enzyme/test/Integration/multivecmax.cpp
enzyme/test/TypeAnalysis/nullcp.ll
enzyme/test/TypeAnalysis/sveci1.ll
enzyme/test/TypeAnalysis/vecptr.ll

This contains a breaking change to the C ABI.

Re-enable attributor and use proper memory management for compiler internals

---

content/getting_started/UsingEnzyme.md

The example code on the website is missing a cast to a void pointer.

Fix example code

---

enzyme/Enzyme/GradientUtils.cpp
enzyme/test/Enzyme/addrbug.ll

I believe this should remedy the julia issue you saw @vchuravy

Fix address space bug in cache LICM

---

enzyme/Enzyme/ActivityAnalysis.h
enzyme/Enzyme/ActivityAnalysisPrinter.cpp
enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/DifferentialUseAnalysis.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/test/Enzyme/callundefinphi2.ll
enzyme/test/Enzyme/metasinfor.ll
enzyme/test/Enzyme/multiout.ll
enzyme/test/Integration/multivecmax.cpp

The mincut heuristic still needs to be aware of loops and potential costs beyond number of values.

Fix Differential Use analysis and introduce mincut recompute heuristic

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/test/Enzyme/condload.ll
enzyme/test/Enzyme/condtriload.ll
enzyme/test/Enzyme/sharedcachefwd.ll

Fix bug in phi recomputation wherein certain recomputations are only conditionally legal (e.g. if passing a bounds check).

Fix PHI Recompute Bug

---

enzyme/Enzyme/GradientUtils.cpp

LULESH motivated optimization improving performance of reverse-pass for `__nv_sqrt` containing code.

Add LULESH-motivated optimization to gradient utils.

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/bitcast.ll
enzyme/test/Enzyme/ForwardMode/fpext.ll

implemented forward mode CastInst
Tests will follow in #198

Forward mode cast inst

---

enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/GradientUtils.h

Cleaning up some basic blocks only needed for reverse mode.

Don't create rBBs for forward mode

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/bsearch.ll
enzyme/test/Enzyme/ForwardMode/bsearch2.ll
enzyme/test/Enzyme/ForwardMode/divreduce.ll
enzyme/test/Enzyme/ForwardMode/divreduce2.ll
enzyme/test/Enzyme/ForwardMode/ge.ll
enzyme/test/Enzyme/ForwardMode/intsum.ll
enzyme/test/Enzyme/ForwardMode/rwloop.ll
enzyme/test/Enzyme/ForwardMode/sumnlist.ll
enzyme/test/Enzyme/ForwardMode/sumsimple.ll
enzyme/test/Enzyme/ForwardMode/sumsimpleoptnone.ll
enzyme/test/Enzyme/ForwardMode/sumsquare.ll
enzyme/test/Enzyme/ForwardMode/sumwithbreak.ll
enzyme/test/Integration/ForwardMode/loops.c
enzyme/test/Integration/ForwardMode/loopsdouble.c
enzyme/test/Integration/ForwardMode/loopstriple.c
enzyme/test/Integration/ForwardMode/rwrloop.c
enzyme/test/Integration/ForwardMode/sumtil.c
enzyme/test/Integration/ForwardMode/sumtil2.c

Added derivative of phi for forward mode

ForwardMode phi

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/benchmarks/gmm/Makefile.make
enzyme/test/Enzyme/ReverseMode/mpi_bcast.ll
enzyme/test/Enzyme/ReverseMode/removeretattr.ll

We should also patch the jll for ease @vchuravy

Fix noundef and other errors

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/FunctionUtils.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/test/Integration/ReverseMode/CMakeLists.txt
enzyme/test/Integration/ReverseMode/mycos.c
enzyme/test/lit.site.cfg.py.in

Additionally fix & simplify accumulation of structs.
As a side note, merging this means there's only one more "based off of LLVM mainline" branch with unmerged commits.

Introduce enzyme_iter for preserving approximation levels through differentiation.

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/fneg.ll

Implement FNeg for Forward Mode

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/test/Enzyme/ReverseMode/unreachableuse.ll

Partially resolves: https://github.com/wsmoses/Enzyme.jl/issues/91

Activity of unreachable use and gemm type

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/test/Enzyme/ReverseMode/putchar.ll

Fixes: https://github.com/wsmoses/Enzyme/issues/240

Handle putchar

---

enzyme/Enzyme/FunctionUtils.cpp

Enable scope AA

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/test/Enzyme/ReverseMode/globalfn.ll

Handle global function array

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/LibraryFuncs.h
enzyme/test/Enzyme/ReverseMode/dbginfo.ll

Add missing debug location for calls to free

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/cosh.ll
enzyme/test/Enzyme/ForwardMode/erf.ll
enzyme/test/Enzyme/ForwardMode/erfc.ll
enzyme/test/Enzyme/ForwardMode/erfi.ll

Forward Mode CallInst known functions

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/Utils.h
enzyme/test/Enzyme/ForwardMode/badcallused.ll
enzyme/test/Enzyme/ForwardMode/badcallused2.ll

Forward Mode TwoReturns

---

enzyme/Enzyme/EnzymeLogic.cpp

Cannot currently be reproduced by ll or c++ tests as this will only occur during Julia split mode where an anonymous tape is requested even if a tape is not necessary at all.

Fix potential null load on empty anonymous struct

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/cos.ll
enzyme/test/Enzyme/ForwardMode/exp.ll
enzyme/test/Enzyme/ForwardMode/exp2.ll
enzyme/test/Enzyme/ForwardMode/experimental_vector_reduce_v2_fadd.ll
enzyme/test/Enzyme/ForwardMode/fabs.ll
enzyme/test/Enzyme/ForwardMode/log.ll
enzyme/test/Enzyme/ForwardMode/log10.ll
enzyme/test/Enzyme/ForwardMode/log2.ll
enzyme/test/Enzyme/ForwardMode/maxnum.ll
enzyme/test/Enzyme/ForwardMode/minnum.ll
enzyme/test/Enzyme/ForwardMode/pow.ll
enzyme/test/Enzyme/ForwardMode/powi.ll
enzyme/test/Enzyme/ForwardMode/sin.ll
enzyme/test/Enzyme/ForwardMode/sqrelu.ll
enzyme/test/Enzyme/ForwardMode/sqrt.ll
enzyme/test/Enzyme/ForwardMode/vector_reduce_fadd.ll
enzyme/test/Enzyme/ReverseMode/experimental_vector_reduce_v2_fadd.ll
enzyme/test/Enzyme/ReverseMode/vector_reduce_fadd.ll

ForwardMode IntrinsicInst

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/CApi.cpp
enzyme/Enzyme/CApi.h
enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/EnzymeLogic.h

Split up CreatePrimalAndGradient and remove the fwd mode stuff

EnzymeLogic cleanup

---

enzyme/Enzyme/EnzymeLogic.cpp
enzyme/test/Integration/ReverseMode/customcombined.c

Resolves https://github.com/wsmoses/Enzyme/issues/327

Use custom reverse in combined mode

---

enzyme/test/Enzyme/ForwardMode/global.ll
enzyme/test/Enzyme/ForwardMode/sumsquare.ll

Fix some tests that were accidentally testing reverse mode instead of forward mode.

Fix Forward Mode Tests

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/square_array.ll

ForwardMode InsertValueInst

---

enzyme/Enzyme/GradientUtils.h

Fixes https://github.com/wsmoses/Enzyme.jl/issues/117

Fix custom allocation handler

---

enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.h
enzyme/test/TypeAnalysis/nonstrict.ll
enzyme/test/TypeAnalysis/nonstrict2.ll

Required for https://github.com/wsmoses/Enzyme.jl/issues/123

Add non-strict aliasing support

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/FunctionUtils.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/test/Enzyme/ForwardMode/maskedload.ll
enzyme/test/Enzyme/ForwardMode/maskedstore.ll
enzyme/test/Enzyme/ReverseMode/maskedload.ll
enzyme/test/Enzyme/ReverseMode/maskedstore.ll

Both forward and reverse mode
Closes #248

Masked load/store support

---

content/getting_started/Faq.md

add opt can't find enzyme problem

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/GradientUtils.h
enzyme/test/Enzyme/ForwardMode/insertvalue.ll
enzyme/test/Enzyme/ReverseMode/insertvalue.ll
enzyme/test/Enzyme/ReverseMode/sret1.ll

ARM Bugfixes

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/calloc.ll

Fix allocs with more than one parameter

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/test/Enzyme/ForwardMode/calloc.ll

this fixes #392, we still need to look deeper into properly supporting dupnoneed.

Handle dupnoneed in forward mode

---

enzyme/test/CMakeLists.txt
enzyme/test/Enzyme/CMakeLists.txt
enzyme/test/Integration/CMakeLists.txt

Run check-enzyme tests in run test suite instead of two.

Make check-enzyme one test suite

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/negbithack.ll
enzyme/test/Enzyme/ForwardMode/negbithack2.ll
enzyme/test/Enzyme/ForwardMode/negbithack3.ll

Handle forward mode bithacks

---

enzyme/Enzyme/CacheUtility.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/test/Enzyme/ReverseMode/rwrloop.ll
enzyme/test/Enzyme/ReverseMode/usedinlastiter.ll
enzyme/test/Enzyme/ReverseMode/vvmax.ll

Fix is last loop iter computation

---

enzyme/Enzyme/ActivityAnalysis.cpp

Hopefully a resolution to gc_preserve_begin phi issue on LLVM 13.

Consider all token returns as inactive values

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/FunctionUtils.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/test/Enzyme/CMakeLists.txt
enzyme/test/Enzyme/ForwardModeVector/CMakeLists.txt
enzyme/test/Enzyme/ForwardModeVector/bitcast.ll

Minimal working example for cast inst + unwrapAndApply family of utility functions and getTypeForVectorMode.

Implement vector mode utils

---

enzyme/Enzyme/AdjointGenerator.h

Something @wsmoses told me to do.

More output

---

enzyme/Enzyme/GradientUtils.cpp
enzyme/test/Enzyme/ReverseMode/threenondomcondition.ll
enzyme/test/Enzyme/ReverseMode/twophi.ll

- Add enzyme_active metadata
- fix edge-case where condition might not be recomputable

three branch

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ReverseMode/jl_powi.ll

- use original powi function
- use original pow function

Use original function instead of new intrinsic

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/CApi.cpp
enzyme/Enzyme/CApi.h
enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/EnzymeLogic.h
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/test/Enzyme/ReverseMode/ompsqloopPostOpt.ll

@vchuravy this requires the requisite Julia change

Move postopt abi

---

enzyme/Enzyme/EnzymeLogic.cpp

Early exists/continue

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/DifferentialUseAnalysis.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/Enzyme/TypeAnalysis/TypeTree.h
enzyme/Enzyme/Utils.h

This may need to evolve with time, but happily most of the functionality is encapsulated in a single helper function.

Attach primal and shadow operand bundles

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/powi13.ll
enzyme/test/Enzyme/ForwardModeVector/powi13.ll
enzyme/test/Enzyme/ReverseMode/jl_powi.ll
enzyme/test/Enzyme/ReverseMode/powi13.ll

powi(x, 0) currently results in a nan.

Fix powi nan

---

.packaging/build_tarballs.jl

Mirror https://github.com/JuliaPackaging/Yggdrasil/pull/4417

Fix JLL buildscript

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/Utils.h
enzyme/test/Enzyme/ForwardMode/mpi/mpi.ll
enzyme/test/Enzyme/ForwardMode/mpi/mpi2.ll
enzyme/test/Enzyme/ForwardMode/mpi/mpi_allgather.ll
enzyme/test/Enzyme/ForwardMode/mpi/mpi_allreduce.ll
enzyme/test/Enzyme/ForwardMode/mpi/mpi_bcast.ll
enzyme/test/Enzyme/ForwardMode/mpi/mpi_gather.ll
enzyme/test/Enzyme/ForwardMode/mpi/mpi_irecv.ll
enzyme/test/Enzyme/ForwardMode/mpi/mpi_scatter.ll
enzyme/test/Integration/ForwardMode/mpi/mpi_bcast.c
enzyme/test/Integration/ForwardMode/mpi/mpi_reduce.c

Forward mode MPI

---

CONTRIBUTING.md

Addition of an initial version of a contribution guide based on the LLVM contribution guide, and pointing to the LLVM code of conduct.

Initial version of contributing guide.

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/CacheUtility.cpp
enzyme/Enzyme/CacheUtility.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/Enzyme/Utils.cpp
enzyme/Enzyme/Utils.h
enzyme/test/Enzyme/ReverseMode/blas/cblas_ddot.ll
enzyme/test/Enzyme/ReverseMode/blas/cblas_sdot.ll
enzyme/test/Enzyme/ReverseMode/callundefinphi2.ll
enzyme/test/Enzyme/ReverseMode/ge.ll
enzyme/test/Enzyme/ReverseMode/incloop.ll
enzyme/test/Enzyme/ReverseMode/mincachechain3.ll
enzyme/test/Enzyme/ReverseMode/ompsqloop.ll
enzyme/test/Enzyme/ReverseMode/ompsqloop2.ll
enzyme/test/Enzyme/ReverseMode/pre-errorsq.ll
enzyme/test/Enzyme/ReverseMode/reversecacheunwrap.ll
enzyme/test/Enzyme/ReverseMode/rwrloop.ll
enzyme/test/Enzyme/ReverseMode/sumnllist.ll

@tansongchen note that the BLAS dot code needs to be extended to allow usage by the fortran-style blas routines in Julia. 
Your routines will need to be similarly extended.
Enables https://github.com/EnzymeAD/Enzyme.jl/pull/237

Functioning FBLAS and TBAA prop

---

.packaging/build_tarballs.jl

Mirror https://github.com/JuliaPackaging/Yggdrasil/pull/4516/

update Enzyme to LLVM platform tag

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/test/Enzyme/ForwardMode/phidbg.ll
enzyme/test/Enzyme/ForwardModeSplit/bsearch2.ll

@jedbrown @LeilaGhaffari this should fix the CEED error you saw.

Fix forward phi debug info

---

enzyme/Enzyme/FunctionUtils.cpp

Resolves https://github.com/EnzymeAD/Enzyme/issues/514

Don't replace within defn

---

enzyme/Enzyme/Enzyme.cpp

Lower calls to __enzyme_autodiff in order

---

enzyme/Enzyme/GradientUtils.cpp
enzyme/test/Enzyme/ReverseMode/headerremat.ll
enzyme/test/Integration/ReverseMode/headerremat.c
enzyme/test/Integration/ReverseMode/ompbound.c

Likely resolves https://github.com/EnzymeAD/Enzyme/issues/570

Fix header rematerialization

---

enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/FunctionUtils.cpp
enzyme/test/Enzyme/ReverseMode/allocnotape.ll

Cleanup preprocessed func

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/GradientUtils.cpp

Note that for the phi, this is only a placeholder fix -- the true fix should unify the invertedPointers and diffe map

Fix vector ConstantDataArray and phi diffe

---

enzyme/Enzyme/EnzymeLogic.cpp
enzyme/test/Enzyme/ReverseMode/unitmemcpy.ll

Solves https://github.com/EnzymeAD/Enzyme.jl/issues/311 until the jl_reshape needing a custom reverse

mark unnecessary mallocs

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/test/Integration/ReverseMode/fbuff.cpp

Should handle the issue you mentioned for now @wsmoses .
I am still looking for a more systematic approach, an official IO testsuite would be nice.

some more IO handling

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/fmuladd.ll
enzyme/test/Enzyme/ReverseMode/fmuladd.ll

@jedbrown @LeilaGhaffari There was more of a bug here (now fixed by this PR) than I saw at first glance in our call today. It's possible this was partially responsible for the nan (and at minimum likely caused an incorrect result).

Fix forward fmuladd

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/fmuladd.ll

@ZuseZ4 fixes https://github.com/EnzymeAD/Enzyme/issues/656
@jedbrown @LeilaGhaffari may also impact the CEED code.

Fix fwd fmuladd

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/Enzyme/CMakeLists.txt

@tgymnich could you please verify if the linking here fixes the compiler explorer?
It worked at least locally for me when loading enzyme trough opt.

test cmake fix

---

enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/test/TypeAnalysis/typesize.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/726

Handle type size specific pattern

---

enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/test/Enzyme/ReverseMode/urem.ll
enzyme/test/TypeAnalysis/urem.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/727

Add urem type support

---

enzyme/Enzyme/AdjointGenerator.h

Provides a better error handler for use in julia

Simplify store type handling

---

.packaging/build_tarballs.jl
enzyme/Enzyme/CMakeLists.txt

x-ref: https://github.com/JuliaPackaging/Yggdrasil/pull/5108

Bootstrap enzyme tblgen

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/test/Enzyme/ForwardMode/cabs-const.ll
enzyme/test/Enzyme/ForwardMode/cabs.ll
enzyme/test/Enzyme/ForwardMode/cabs2-const.ll
enzyme/test/Enzyme/ForwardMode/cabs2.ll
enzyme/test/Enzyme/ForwardModeVector/cabs.ll
enzyme/test/Enzyme/ForwardModeVector/cabs2.ll
enzyme/test/Enzyme/ReverseMode/cabs-const.ll
enzyme/test/Enzyme/ReverseMode/cabs2-const.ll
enzyme/test/Enzyme/ReverseMode/cabs2.ll

Cabs calling convention

---

enzyme/Enzyme/Enzyme.cpp
enzyme/test/Enzyme/ReverseMode/constarg.ll

Hopefully the last OpenLB related issue.

indirect enzyme_const loads

---

enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/test/Enzyme/ReverseMode/constexpr.ll
enzyme/test/Enzyme/ReverseMode/previdxout.ll

Fixes https://github.com/EnzymeAD/Enzyme.jl/issues/388
fixes #752

Fix previdx calculation

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/test/ActivityAnalysis/atomicrmw.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/706

Fix activity analysis loop

---

enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/test/TypeAnalysis/forgepsz.ll
enzyme/test/TypeAnalysis/forgepsz2.ll
enzyme/test/TypeAnalysis/forgepsz3.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/758

Fast loop affine integer calculation

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ReverseMode/recurmapinc.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/786

Fix recursive map inversion

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/CApi.cpp
enzyme/Enzyme/CApi.h
enzyme/Enzyme/DifferentialUseAnalysis.h
enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/FunctionUtils.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/Enzyme/LibraryFuncs.h
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/Enzyme/Utils.cpp
enzyme/Enzyme/Utils.h

Technically solves: https://github.com/EnzymeAD/Enzyme/issues/808  Though that program is in error regardless

Simplify function detection API

---

enzyme/Enzyme/DifferentialUseAnalysis.h
enzyme/test/Enzyme/ReverseMode/inactivememcpy.ll

Fixes https://github.com/EnzymeAD/Enzyme.jl/issues/429

Inactive memcpy src, but active dst diffeuse

---

enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/InstructionDerivatives.td
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/test/Enzyme/ForwardModeVector/constret.ll
enzyme/test/Enzyme/ReverseMode/sinc.ll

Partial fix for https://github.com/EnzymeAD/Enzyme.jl/issues/434

Fix sinc related bugs

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/test/TypeAnalysis/canonwidth.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/782

Fix shuffle canonicalization

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/GradientUtils.cpp
enzyme/test/Enzyme/ReverseMode/callseg.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/820

Fix call segfault

---

enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/EnzymeLogic.h
enzyme/test/Enzyme/ReverseMode/cacheErr.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/798

Fix recursive cache reverse

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ReverseMode/indirectcst.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/829

Permit inactive register arguments on an indirect call

---

enzyme/BCLoad/CMakeLists.txt

Needed to fix https://github.com/EnzymeAD/Enzyme.jl/issues/445

Bump BCLoad gsl to not use short circuiting blas

---

enzyme/CMakeLists.txt
enzyme/Enzyme/GradientUtils.cpp
enzyme/test/Enzyme/ReverseMode/ompcache.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/844

Fix omp cache case

---

enzyme/Enzyme/DifferentialUseAnalysis.h

Fixes https://github.com/EnzymeAD/Enzyme.jl/issues/510

Fix mincut remat bug

---

enzyme/Enzyme/GradientUtils.h

Possible fix for: https://github.com/EnzymeAD/Enzyme.jl/issues/431

Fix vector atomic gep

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/GradientUtils.cpp

Cleanup and fix macos

---

enzyme/Enzyme/GradientUtils.cpp

Fixes https://github.com/EnzymeAD/Enzyme/issues/927

Add constantexpr shadow

---

Readme.md

Adding the  SC'22 citation to the README, plus adding a preceding pointer to with regards to when one should cite said paper.

Addition of SC'22 citation to Readme

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/Enzyme/MLIR/Dialect/EnzymeOps.td
enzyme/Enzyme/MLIR/Interfaces/GradientUtils.cpp
enzyme/Enzyme/MLIR/Passes/EnzymeMLIRPass.cpp

Fix recent renames in LLVM 16

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/LibraryFuncs.h
enzyme/Enzyme/PreserveNVVM.cpp
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/Enzyme/Utils.h
enzyme/test/Integration/ReverseMode/customalloc.c

Resolves https://github.com/EnzymeAD/Enzyme/issues/930

Support declaring a custom allocation / free function.

---

.github/workflows/benchmark.yml
.gitignore
enzyme/benchmarks/CMakeLists.txt
enzyme/benchmarks/ReverseMode/adbench/ba.h
enzyme/benchmarks/ReverseMode/adbench/gmm.h
enzyme/benchmarks/ReverseMode/adbench/hand.h
enzyme/benchmarks/ReverseMode/adbench/lstm.h
enzyme/benchmarks/ReverseMode/ba/Makefile.make
enzyme/benchmarks/ReverseMode/ba/Makefile.makeafter
enzyme/benchmarks/ReverseMode/gmm/Makefile.make
enzyme/benchmarks/ReverseMode/gmm/Makefile.makeafter
enzyme/benchmarks/ReverseMode/hand/Makefile.make
enzyme/benchmarks/ReverseMode/lstm/Makefile.make
enzyme/benchmarks/ReverseMode/lstm/Makefile.makeafter
enzyme/benchmarks/json.hpp
enzyme/benchmarks/upload-results.py

Graph ADBench benchmarks

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/frexp.ll
enzyme/test/Enzyme/ReverseMode/frexp.ll
enzyme/test/Integration/ReverseMode/frexp.c

Implement frexp

---

enzyme/Enzyme/PreserveNVVM.cpp

Fixes https://github.com/EnzymeAD/Enzyme/issues/968

Handle compiler.used

---

enzyme/Enzyme/TraceUtils.h
enzyme/test/Enzyme/ProbProg/condition-dynamic.ll
enzyme/test/Enzyme/ProbProg/condition-static.ll
enzyme/test/Enzyme/ProbProg/simple-condition.ll
enzyme/test/Enzyme/ProbProg/simple-trace.ll
enzyme/test/Enzyme/ProbProg/trace-dynamic.ll
enzyme/test/Enzyme/ProbProg/trace-static.ll

Remove unnecessary `alloca` and `store` when passing choice value inside the bits of a pointer.

Fix insert choice

---

.packaging/build_tarballs.jl

x-ref: https://github.com/JuliaPackaging/Yggdrasil/pull/6270#issuecomment-1433005714

Upgrade to OSX 10.14 for jll

---

enzyme/Enzyme/Enzyme.cpp

for future reuse in prob prog.

Extract populate_overwritten_args

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp

remove orig aliasing call reference

---

enzyme/Enzyme/AdjointGenerator.h

Make `visitCallInst` just a tiny bit smaller

Extract handle unknown function

---

enzyme/Enzyme/Enzyme.cpp

Rewrite ReplaceOriginalCall

---

enzyme/Enzyme/ActivityAnalysis.cpp

Fixes https://github.com/EnzymeAD/Enzyme/issues/1041

[Activity Analysis] handle global alias

---

enzyme/Enzyme/CMakeLists.txt

should have no real perf impact since we only have 42 files in that directory
fixes https://github.com/EnzymeAD/Enzyme/issues/1051

force glob re-run

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h

Will be necessary when external rules have opaque pointers for tape.

Fix ignoretype

---

enzyme/Enzyme/AdjointGenerator.h

Remove `using namespace llvm` from `AdjointGenerator`

---

enzyme/Enzyme/FunctionUtils.cpp
enzyme/test/Enzyme/ReverseMode/bounds.ll
enzyme/test/Enzyme/ReverseMode/bounds2.ll
enzyme/test/Enzyme/ReverseMode/callundefinphi2.ll
enzyme/test/Enzyme/ReverseMode/dynamicphi.ll
enzyme/test/Enzyme/ReverseMode/loopcanon.ll
enzyme/test/Enzyme/ReverseMode/usedinlastiter.ll

Fix loop simplify assumption

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/test/ActivityAnalysis/funname.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/1088

Activity analysis check funcname

---

enzyme/Enzyme/DifferentialUseAnalysis.h
enzyme/test/Enzyme/ForwardMode/freeuse.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/1101

Ensure free args kept in fwd mode

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/EnzymeLogic.cpp

Fixes https://github.com/EnzymeAD/Enzyme.jl/issues/716

Reorder loop initialization to occur after cacheanalysis

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/TraceGenerator.cpp
enzyme/Enzyme/TraceGenerator.h
enzyme/Enzyme/TraceInterface.cpp
enzyme/Enzyme/TraceInterface.h
enzyme/Enzyme/TraceUtils.cpp
enzyme/Enzyme/TraceUtils.h
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/test/Enzyme/ProbProg/condition-dynamic.ll
enzyme/test/Enzyme/ProbProg/condition-static.ll
enzyme/test/Enzyme/ProbProg/simple-condition-diff.ll
enzyme/test/Enzyme/ProbProg/simple-condition.ll
enzyme/test/Enzyme/ProbProg/simple-trace-diff.ll
enzyme/test/Enzyme/ProbProg/simple-trace.ll
enzyme/test/Enzyme/ProbProg/trace-dynamic.ll
enzyme/test/Enzyme/ProbProg/trace-static.ll

- add `insertArgument`
- add `insertReturn`
- add  `insertFunction(Pointer)`

Prob trace extension

---

enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/Enzyme/TypeAnalysis/TypeTree.h
enzyme/test/TypeAnalysis/canon.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/1141

Fix TT canonicalization

---

enzyme/Enzyme/CApi.cpp
enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/Utils.h

@ZuseZ4 this is where the TG blas attributes should be added.

Add attribute known function cabi

---

enzyme/Enzyme/CMakeLists.txt
enzyme/Enzyme/DifferentialUseAnalysis.cpp
enzyme/tools/enzyme-tblgen/blasDiffUseUpdater.h
enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp

I'll need to update that probably once I have more rules, but that doesn't make much sense now as I don't have the extra rules to test it yet.

add simple DiffUse tblgen

---

enzyme/Enzyme/Enzyme.cpp
enzyme/test/Integration/ForwardMode/nofn.cpp

Fixes https://github.com/EnzymeAD/Enzyme/issues/1186

Fix error message for nofn to d/dx

---

enzyme/Enzyme/Utils.cpp
enzyme/test/Enzyme/ReverseMode/blas/cblas_ddot.ll
enzyme/test/Enzyme/ReverseMode/blas/cblas_ddot64_.ll
enzyme/test/Enzyme/ReverseMode/blas/cblas_sdot.ll
enzyme/test/Enzyme/ReverseMode/blas/vec_cblas_ddot.ll
enzyme/test/Enzyme/Sparse/indir.ll

fixes https://github.com/EnzymeAD/Enzyme.jl/pull/842

handle negative strides in memcpy

---

enzyme/Enzyme/Utils.cpp
enzyme/Enzyme/Utils.h
enzyme/tools/enzyme-tblgen/caching.h
enzyme/tools/enzyme-tblgen/datastructures.h

Julia mixes both cblas and fortran abi.
copy is based on fortran.

handle julia blas

---

enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/Utils.h
enzyme/test/Enzyme/ReverseMode/missingstore.ll

@vchuravy 
Partially resolves GC error. Still will persist in https://fwd.gymni.ch/2gQwUv

Fix calling conv attribution mismatch

---

enzyme/test/Enzyme/ReverseMode/blas/gemv_f_c_split_blascpy.ll

Based on what made CI failed in the last run.
Still not sure why it's not running, can't see the apple runners do anything here: https://github.com/EnzymeAD/Enzyme/actions/workflows/enzyme-ci.yml

fix apple ci

---

enzyme/Enzyme/PreserveNVVM.cpp

Check for null pointer for index argument of __enzyme_allocation_like

---

enzyme/Enzyme/BlasDerivatives.td
enzyme/test/Enzyme/ReverseMode/blas/gemv_f_c_split_blascpy.ll

Lets' factor this bugfix out of https://github.com/EnzymeAD/Enzyme/pull/1310/files

fix type of 1 in blas gemv call

---

enzyme/Enzyme/Enzyme.cpp

Add missing check for aggregate type

---

enzyme/Enzyme/AdjointGenerator.h

Fixes https://github.com/EnzymeAD/Enzyme.jl/issues/1009

Fix runtime memtransfer assertion into a julia rule

---

enzyme/Enzyme/ActivityAnalysis.cpp
enzyme/test/ActivityAnalysis/allocindircall.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/1406

Fix indirect call activity

---

enzyme/Enzyme/CApi.cpp
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.h
enzyme/Enzyme/TypeAnalysis/TypeTree.h
enzyme/test/TypeAnalysis/floatintload.ll
enzyme/test/TypeAnalysis/sharedmem.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/1393

Fix lookup normalization

---

enzyme/test/Integration/ReverseMode/invsqrt.c

Previous code always returned 0 for 64 bit longs.

fix invsqrt example

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/DiffeGradientUtils.cpp
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.h

Changing some assertions into normal compile time errors.

Better c++ errors

---

enzyme/Enzyme/AdjointGenerator.h

Fixes https://github.com/EnzymeAD/rust/issues/16

Handle memset of undef memory, even if not type analyzable

---

enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp

Fixes https://github.com/EnzymeAD/Enzyme.jl/issues/1020

Special case gep of small_typeof

---

enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp
enzyme/Enzyme/TypeAnalysis/TypeAnalysis.h
enzyme/Enzyme/TypeAnalysis/TypeTree.h
enzyme/test/Enzyme/ReverseMode/infanalysis.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/1402

Speed up and fix type analysis merges

---

enzyme/Enzyme/BlasDerivatives.td
enzyme/test/Enzyme/ReverseMode/blas/gemv_c_loop2.ll
enzyme/test/Enzyme/ReverseMode/blas/gemv_c_loop3_matcopy.ll
enzyme/test/Enzyme/ReverseMode/blas/gemv_f_c_split_blascpy.ll
enzyme/test/Enzyme/ReverseMode/blas/gemv_f_c_split_blascpy_runtime_act.ll
enzyme/test/Enzyme/ReverseMode/blas/gemv_f_c_split_memcpy.ll
enzyme/tools/enzyme-tblgen/blas-tblgen.cpp

cc @wsmoses 
This + small adjustments to your PR should fix gemv.
WIP

fix gemv rule for A

---

.github/workflows/doxygen.yml
enzyme/Enzyme/Clang/EnzymePassLoader.cpp
enzyme/Enzyme/Enzyme.cpp

Add flag to disable AD.

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/DifferentialUseAnalysis.cpp
enzyme/Enzyme/DifferentialUseAnalysis.h
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/InstructionDerivatives.td
enzyme/Enzyme/Utils.h
enzyme/test/Enzyme/ForwardMode/frexp.ll
enzyme/test/Enzyme/ReverseMode/infAlloc.ll
enzyme/tools/enzyme-tblgen/blasDiffUseUpdater.h
enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp

@ludgerpaehler see if using this improves the alpaca stuff.
Regardless, this should also introduce some better logging for -enzyme-print-diffuse and -enzyme-unnecessary to try to find the root cause of the issue you saw.

Tblgen diffuse

---

.packaging/build_tarballs.jl

https://github.com/JuliaPackaging/Yggdrasil/pull/7588

Support building in Yggdrasil with LLVM 16

---

enzyme/Enzyme/AdjointGenerator.h
enzyme/test/Enzyme/ForwardMode/memcpyanyflt.ll

Fixes https://github.com/EnzymeAD/Enzyme.jl/issues/1118

Fix memcpy derivative for any/float combo

---

enzyme/Enzyme/TypeAnalysis/TypeTree.h

Get rid of quite a few allocations by using `make_early_inc_range`

Use early_inc_range

---

enzyme/Enzyme/ActivityAnalysis.cpp

This is the one-line change suggested in https://github.com/EnzymeAD/Enzyme/issues/1599#issuecomment-1875177062 which fixes #1599.

Fix printing bug #1599

---

.github/workflows/enzyme-mlir.yml
enzyme/Enzyme/MLIR/enzymemlir-translate/enzymemlir-translate.cpp

The relevant changes from the @pengmai fork have been integrated.

rebase MLIR-Enzyme back on upstream LLVM

---

enzyme/CMakeLists.txt

Let's see if this passes CI. Credits to @OwenTrokeBillard

make fpic work on windows

---

.github/workflows/enzyme-ci.yml

Fix macOS CI

---

.devcontainer/devcontainer.json
.gitignore
enzyme/CMakeLists.txt

- nicer autocomplete and errors in vscode

Enable clangd support

---

.github/workflows/tagger.yml

replace this:
https://github.com/actions/create-github-app-token
with that:
https://github.com/tibdex/github-app-token

Replace third party create-github-app-token action with official action

---

enzyme/Enzyme/Enzyme.cpp

Fixed incorrect usage of llvm::Function::splice.

---

enzyme/Enzyme/EnzymeLogic.cpp
enzyme/test/Enzyme/ReverseMode/dacsum.ll

Fixes https://github.com/EnzymeAD/Enzyme/issues/1873

Optimize away unused direct recursive tapes

---

enzyme/Enzyme/CApi.h

add EnzymeCreateForwardDiff to CApi.h #1923

---

enzyme/Enzyme/MLIR/Implementations/BuiltinAutoDiffTypeInterfaceImpl.cpp
enzyme/Enzyme/MLIR/Implementations/CMakeLists.txt
enzyme/Enzyme/MLIR/Implementations/Common.td
enzyme/Enzyme/MLIR/Implementations/ComplexAutoDiffOpInterfaceImpl.cpp
enzyme/Enzyme/MLIR/Implementations/ComplexDerivatives.td
enzyme/Enzyme/MLIR/Implementations/CoreDialectsAutoDiffImplementations.cpp
enzyme/Enzyme/MLIR/Implementations/CoreDialectsAutoDiffImplementations.h
enzyme/Enzyme/MLIR/Implementations/LLVMAutoDiffOpInterfaceImpl.cpp
enzyme/Enzyme/MLIR/Implementations/MemRefAutoDiffOpInterfaceImpl.cpp
enzyme/Enzyme/MLIR/Interfaces/AutoDiffTypeInterface.td
enzyme/Enzyme/MLIR/Passes/SimplifyMath.cpp
enzyme/Enzyme/MLIR/enzymemlir-opt.cpp
enzyme/test/MLIR/ReverseMode/csquare.mlir
enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp

MLIR: complex

---

enzyme/Enzyme/MLIR/Dialect/EnzymeOps.td
enzyme/Enzyme/MLIR/Dialect/Ops.cpp
enzyme/Enzyme/MLIR/Interfaces/CloneFunction.cpp
enzyme/Enzyme/MLIR/Interfaces/CloneFunction.h
enzyme/Enzyme/MLIR/Passes/CMakeLists.txt
enzyme/Enzyme/MLIR/Passes/EnzymeBatchPass.cpp
enzyme/Enzyme/MLIR/Passes/Passes.h
enzyme/Enzyme/MLIR/Passes/Passes.td
enzyme/test/MLIR/Batch/CMakeLists.txt
enzyme/test/MLIR/Batch/add.mlir

Add batching pass

---

enzyme/Enzyme/MLIR/Implementations/ArithAutoDiffOpInterfaceImpl.cpp
enzyme/Enzyme/MLIR/Interfaces/AutoDiffOpInterface.h
enzyme/Enzyme/MLIR/Interfaces/AutoDiffOpInterface.td
enzyme/Enzyme/MLIR/Interfaces/CloneFunction.cpp
enzyme/test/MLIR/Batch/addconst.mlir

@avik-pal @Pangoraw part one of two [we also need to push the interface use into hlo]

MLIR: add constant batching

---

enzyme/Enzyme/ActivityAnalysis.cpp

- `std::unique_ptr` does not use atomics
- `std::unique_ptr` does not need to keep track of a refcount

Use std::unique_ptr instead of std::shared_ptr

---

enzyme/Enzyme/DifferentialUseAnalysis.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/GradientUtils.h
enzyme/test/Enzyme/ReverseMode/nulload.ll

@gbaraldi this was the resolution to the segfault [tho non-determinism is unclear]

Rematerializer: fix recursive rematerialization error

---

enzyme/Enzyme/Enzyme.cpp

The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @eelenberg, @jweese, and @fwph. This PR updates memory allocation in `EnzymeBase::HandleProbProg` and `EnzymeBase::lowerEnzymeCalls` by using `std::unique_ptr` to manage `interface` and `AC` instead of raw pointers. 
This also fixes a possible bug where `HandleProbProg` could return `true` before `interface` is deleted.
on-behalf-of: @permanence-ai <github-ai@permanence.ai>

improve memory management safety for Enzyme.cpp

---

enzyme/Enzyme/InstructionDerivatives.td

Add __nv_fast_expf to InstructionDerivatives.td

---

enzyme/Enzyme/MustExitScalarEvolution.cpp

Update MustExitScalarEvolution.cpp for upstream LLVM changes

---

.github/workflows/enzyme-mlir.yml
enzyme/Enzyme/AdjointGenerator.h
enzyme/Enzyme/CallDerivatives.cpp
enzyme/Enzyme/DiffeGradientUtils.cpp
enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/EnzymeLogic.cpp
enzyme/Enzyme/FunctionUtils.cpp
enzyme/Enzyme/GradientUtils.cpp
enzyme/Enzyme/LibraryFuncs.h
enzyme/Enzyme/MLIR/Analysis/CMakeLists.txt
enzyme/Enzyme/MLIR/Analysis/DataFlowActivityAnalysis.cpp
enzyme/Enzyme/MLIR/Analysis/DataFlowAliasAnalysis.cpp
enzyme/Enzyme/MLIR/Analysis/DataFlowAliasAnalysis.h
enzyme/Enzyme/MLIR/Passes/PrintAliasAnalysis.cpp
enzyme/Enzyme/Utils.cpp
enzyme/Enzyme/Utils.h
enzyme/tools/enzyme-tblgen/blas-tblgen.cpp
enzyme/tools/enzyme-tblgen/caching.cpp
enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp

@ftynse @pengmai can you review the dataflow changes?

LLVM integrate for mlir changes

---

enzyme/Enzyme/MLIR/Dialect/EnzymeOps.td
enzyme/Enzyme/MLIR/Dialect/Ops.h
enzyme/Enzyme/MLIR/Passes/EnzymeMLIRPass.cpp

Originally opened here https://github.com/EnzymeAD/Enzyme/pull/2172

Support batching in MLIR autodiff operations (2nd try)

---

enzyme/Enzyme/CApi.h

I would like to use the EnzymeCreatePrimalAndGradient function, but it is not declared in the CApi header, this PR adds it.

 add EnzymeCreatePrimalAndGradient to CApi.h

---

enzyme/Enzyme/Clang/EnzymeClang.cpp
enzyme/Enzyme/Enzyme.cpp
enzyme/Enzyme/eopt.cpp

mark registerEnzyme as extern "C"

---

.github/workflows/benchmark.yml

feature is not really used so disable it.

Disable benchmark results upload

---

.github/workflows/fortran.yml

- ubuntu 20 is soon deprecated.

improve fortran ci

---

.github/workflows/format.yml

improve clang format ci

---

enzyme/Enzyme/FunctionUtils.cpp

fix-crash-by-coalese

---

enzyme/tools/enzyme-tblgen/enzyme-tblgen.cpp

Closes #2301.
Example of the generated interface:
```cpp
struct GatherOpActivity : 
public ActivityOpInterface::ExternalModel<GatherOpActivity, stablehlo::GatherOp> {
bool isInactive(mlir::Operation *) const { return false; }
bool isArgInactive(mlir::Operation *op, size_t arg) const {
if (arg == 1) { return true; }
return false;
}
};
struct SelectOpActivity : 
public ActivityOpInterface::ExternalModel<SelectOpActivity, stablehlo::SelectOp> {
bool isInactive(mlir::Operation *) const { return false; }
bool isArgInactive(mlir::Operation *op, size_t arg) const {
if (arg == 0) { return true; }
return false;
}
};

tblgen: Auto-generate ActivityOpInterface

---

enzyme/BUILD
enzyme/WORKSPACE

Generates a compilation database (useful for lsp)

Bazel: generate compile_commands.json

---

enzyme/Enzyme/MLIR/Analysis/ActivityAnalysis.cpp
enzyme/Enzyme/MLIR/enzymemlir-translate/CMakeLists.txt

fixes https://github.com/EnzymeAD/Enzyme/issues/2341

[MLIR][ActivityAnalysis] fix getFunctionIfArgument

---

enzyme/Enzyme/MLIR/Passes/EnzymeMLIRPass.cpp

@ftynse whats the best way to emit the error here

[MLIR] Add nicer error messages for mismatched arguments

---

enzyme/Enzyme/MLIR/Passes/EnzymeBatchPass.cpp

seems to fix the weird name mangling

[MLIR] fix: cast to string

---

enzyme/WORKSPACE

update compile commands version

update compile commands version

---

.github/workflows/enzyme-mlir.yml
enzyme/Enzyme/MLIR/Analysis/CMakeLists.txt
enzyme/Enzyme/MLIR/Analysis/DataFlowActivityAnalysis.cpp

copyop interface was removed by mehdi

LLVM integrate
